### ISSUE TITLE
Update TrioSet.Rd

### ISSUE THREAD

**Issue by syounkin** [syounkin/Trioconductor#4]
Rob, could you edit TrioSet.Rd to be more specific.  For instance, logr and baf are specified simply as matrices.  What should the dimension be?  Do the columns have to be F,M,O?  I think a data.frame with names F, M and O is less ambiguous than a matrix.  What class should F, M and O be?  And so on...

Thanks.

**Comment by rscharpf** [comment]
The inputs to the TrioSet constructor are matrices, since this is what people start with.  In the example, we have

```
path <- system.file("extdata", package="MinimumDistance")
load(file.path(path, "logRratio.rda"))
load(file.path(path, "baf.rda"))
load(file.path(path, "pedigreeInfo.rda"))
trioSet <- TrioSet(lrr=logRratio,
           baf=baf,
           pedigree=Pedigree(pedigreeInfo),
           cdfname="human610quadv1bCrlmm",
           genome="hg18")
```

Note that

```
 > colnames(logRratio)
[1] "NA06993" "NA06985" "NA06991" "NA11881" "NA11882" "NA10859"
> colnames(baf)
[1] "NA06993" "NA06985" "NA06991" "NA11881" "NA11882" "NA10859"
> load(file.path(path, "pedigreeInfo.rda"))
 load(file.path(path, "pedigreeInfo.rda"))
> pedigreeInfo
        F       M       O
1 NA06993 NA06985 NA06991
2 NA11881 NA11882 NA10859
```

I agree that it would be more informative to have labels "father", "mother", and "offfspring" labels instead of "F", "M", "O".   I don't know what you mean by the class of F, M, and O (?)  You can redefine the labels in the Pedigree constructor. 

The assay data elements in TrioSet (log R ratios and BAFs) are 3-dimensional arrays.  The 3rd dimension is the individual label, which we can also change to be "father", "mother", and "offspring".  We do not want to store the assay data as data.frames.

Rob
